import { Roboto } from "next/font/google";
import "@/styles/globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { AuthProvider } from "@/context/AuthContext";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "QuizGenerate",
  description: "Generated by create next app",
  icon: "/favico.png",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="es">
        <head>
          <link rel="icon" href="/favicon.png" type="image/png" />
        </head>

        <body className={`${roboto.variable} antialiased`}>
          <div className="grid-rows-layout">
            <header>
              <Header />
            </header>

            <main>{children}</main>

            <footer>
              <Footer />
            </footer>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
