version: '3.9'

services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - db
    restart: always


  db:
    image: postgres:14.11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tfg_db
      POSTGRES_USER: tfg_user
      POSTGRES_PASSWORD: tfg_user_password
    restart: always


  nginx:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Certificados
    depends_on:
      - backend
    restart: always


volumes:
  postgres_data:
