# Generated by Django 5.1.5 on 2025-03-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_rename_user_quiz_author_quiz_created_at_quiz_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
